### ISSUE TITLE
inmemory.js exports Repository instead of InMemory

### ISSUE THREAD

**Issue by hilkeheremans** [adrai/node-viewmodel#45]
I was out creating view models and since I like to write unit tests, I use the `InMemory` store for those. I then noticed I couldn't access view models, even if I provided the `collectionName`.

As it turns out, if you inspect `lib/databases/inmemory.js` you will find that:

- It (accidentally?) exports `Repository` instead of `InMemory`
- It does not set `this.collectionName` in the `InMemory` constructor, which will prevent it from working in a proper test scenario

I'm surprised the unit tests don't catch this. 

Would you like a PR?

**Comment by adrai** [comment]
v1.5.14
