### ISSUE TITLE
Add support for aggregation function

### ISSUE THREAD

**Issue by xander-mbaka** [adrai/node-viewmodel#49]
viewmodel->lib->databases

aggregate: function(pipeline, options, callback) {

    this.checkConnection();

    var self = this;

    this.collection.aggregate(pipeline, options, function(err, data) {
      if (err) {
        return callback(err);
      }

      if (!data) {
        return callback(null, null);
      }

      var vm = new ViewModel(data, self);
      vm.actionOnCommit = 'update';
      callback(null, vm);
    });

  },

**Comment by xander-mbaka** [comment]
Hi,

Could this feature be integrated for mongodb?

I understand that the other databases dont feature an aggregation pipeline, but in mongodb its essential.

The vm package can then have a list of specialized functions exposed for specific databases.

Or alternatively, how can one inject specific db functionality at the application level to the repository object? 

Kindly assist.

**Comment by adrai** [comment]
Isn't it possible for you to directly access the collection property and call aggregate yourself?

**Comment by xander-mbaka** [comment]
Thanks. I dint know about the collection.
